In [156]:
# import libraries
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
print("importing is done")

importing is done


In [157]:
#load the dataset
df=pd.read_csv('insurance.csv')

In [158]:
# summarizing the dataset
df

age     sex     bmi  children smoker     region      charges
0      19  female  27.900         0    yes  southwest  16884.92400
1      18    male  33.770         1     no  southeast   1725.55230
2      28    male  33.000         3     no  southeast   4449.46200
3      33    male  22.705         0     no  northwest  21984.47061
4      32    male  28.880         0     no  northwest   3866.85520
...   ...     ...     ...       ...    ...        ...          ...
1333   50    male  30.970         3     no  northwest  10600.54830
1334   18  female  31.920         0     no  northeast   2205.98080
1335   18  female  36.850         0     no  southeast   1629.83350
1336   21  female  25.800         0     no  southwest   2007.94500
1337   61  female  29.070         0    yes  northwest  29141.36030

[1338 rows x 7 columns]

In [159]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1338 entries, 0 to 1337
Data columns (total 7 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   age       1338 non-null   int64  
 1   sex       1338 non-null   object 
 2   bmi       1338 non-null   float64
 3   children  1338 non-null   int64  
 4   smoker    1338 non-null   object 
 5   region    1338 non-null   object 
 6   charges   1338 non-null   float64
dtypes: float64(2), int64(2), object(3)
memory usage: 73.3+ KB


In [160]:
df.describe()

age          bmi     children       charges
count  1338.000000  1338.000000  1338.000000   1338.000000
mean     39.207025    30.663397     1.094918  13270.422265
std      14.049960     6.098187     1.205493  12110.011237
min      18.000000    15.960000     0.000000   1121.873900
25%      27.000000    26.296250     0.000000   4740.287150
50%      39.000000    30.400000     1.000000   9382.033000
75%      51.000000    34.693750     2.000000  16639.912515
max      64.000000    53.130000     5.000000  63770.428010

In [161]:
len(df)

1338

In [162]:
df.dtypes

age           int64
sex          object
bmi         float64
children      int64
smoker       object
region       object
charges     float64
dtype: object

In [163]:
# wwe have  columns with object values which we have to convert to integer

In [164]:
# pre-processing the dataset
# first we check for null values
df.isnull().sum().max()

0

In [165]:
# we import new libraries to encode the columns with value as object
from sklearn import preprocessing
from sklearn.preprocessing import LabelEncoder

In [166]:
label = LabelEncoder()
label

LabelEncoder()

In [167]:
# List of columns to encode
columns_to_encode = ['sex', 'smoker','region']

In [168]:
# Apply label encoding to each column to be encoded
df[columns_to_encode]=df[columns_to_encode].apply(LabelEncoder().fit_transform)

In [169]:
#this is the final dataset with all integer values
df

age  sex     bmi  children  smoker  region      charges
0      19    0  27.900         0       1       3  16884.92400
1      18    1  33.770         1       0       2   1725.55230
2      28    1  33.000         3       0       2   4449.46200
3      33    1  22.705         0       0       1  21984.47061
4      32    1  28.880         0       0       1   3866.85520
...   ...  ...     ...       ...     ...     ...          ...
1333   50    1  30.970         3       0       1  10600.54830
1334   18    0  31.920         0       0       0   2205.98080
1335   18    0  36.850         0       0       2   1629.83350
1336   21    0  25.800         0       0       3   2007.94500
1337   61    0  29.070         0       1       1  29141.36030

[1338 rows x 7 columns]

In [170]:
# we confrm the type of value of the sex column
type(df.sex)

pandas.core.series.Series

In [171]:
# Now we create x (input) and y (output) variable
x=df.iloc[:,:-1].values
y=df.iloc[:,-1].values

In [172]:
x

array([[19.  ,  0.  , 27.9 ,  0.  ,  1.  ,  3.  ],
       [18.  ,  1.  , 33.77,  1.  ,  0.  ,  2.  ],
       [28.  ,  1.  , 33.  ,  3.  ,  0.  ,  2.  ],
       ...,
       [18.  ,  0.  , 36.85,  0.  ,  0.  ,  2.  ],
       [21.  ,  0.  , 25.8 ,  0.  ,  0.  ,  3.  ],
       [61.  ,  0.  , 29.07,  0.  ,  1.  ,  1.  ]])

In [173]:
y

array([16884.924 ,  1725.5523,  4449.462 , ...,  1629.8335,  2007.945 ,
       29141.3603])

In [174]:
# now we import additionl required libraries
from sklearn.model_selection import train_test_split
from sklearn.ensemble import GradientBoostingRegressor
from sklearn.metrics import mean_squared_error
print("importing is done")

importing is done


In [175]:
# now we create training and testing dataset
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)

In [176]:
x_train.shape,x_test.shape,y_train.shape,y_test.shape

((1070, 6), (268, 6), (1070,), (268,))

In [194]:
x_test

array([[45.   ,  0.   , 25.175,  2.   ,  0.   ,  0.   ],
       [36.   ,  0.   , 30.02 ,  0.   ,  0.   ,  1.   ],
       [64.   ,  0.   , 26.885,  0.   ,  1.   ,  1.   ],
       ...,
       [18.   ,  0.   , 28.215,  0.   ,  0.   ,  0.   ],
       [58.   ,  1.   , 36.08 ,  0.   ,  0.   ,  2.   ],
       [20.   ,  1.   , 22.   ,  1.   ,  0.   ,  3.   ]])

In [177]:
model_i = GradientBoostingRegressor()
model_i

GradientBoostingRegressor()

In [204]:
# we fit the training data in our model
model_i.fit(x_train,y_train)

GradientBoostingRegressor()

In [205]:
# Now testing new Model prediction by providing Test Data set
y_i = model_i.predict(x_test)

In [206]:
# this is our variable which has learned the test data
y_i

array([10613.51249559,  5680.4342457 , 29627.69439108,  9541.85252649,
       34327.94325127,  4962.3508465 ,  2299.40102111, 16070.7350595 ,
        4330.24331921, 11071.50277052, 18631.98027446,  7567.38807257,
        4459.23189637, 45865.55619837, 47105.23965952, 45377.43181479,
       11766.50422421, 45490.8041926 ,  9099.86497246, 24190.51024892,
        6070.53804118,  8877.08734464,  1846.27745351,  4342.89005009,
       11844.87104146, 12415.40689777, 14418.19983619,  6966.38395145,
       11873.80325058,  3346.84494876,  7496.7973755 , 12022.39885384,
        3104.19747569,  6225.84174375,  4928.57061977, 10177.92920393,
        4115.75230999,  8484.595674  , 26761.11967517, 40717.20546526,
        5656.55838911,  4534.36929011, 13593.28619931, 14312.66384893,
        6686.55100825, 16068.3231131 ,  6096.62386646,  6450.78526151,
       42989.71303551,  5823.70542022, 14322.21177735,  2251.81397234,
        6962.98686947,  2507.35708549, 12202.58694563, 12005.01414558,
      

In [207]:
# Compare predictions with testing data given
# this will only give accuracy
mse = mean_squared_error(y_test, y_i)
print(mse)

19164439.64408805


In [208]:
# if we keep split as 70/30
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.3,random_state=42)
model_i = GradientBoostingRegressor()
model_i.fit(x_train,y_train)
y_i = model_i.predict(x_test)
mse = mean_squared_error(y_test, y_i)
print(mse)

19169660.713312637


In [209]:
# Predicting the output of single test data using our trained model
y_test

array([ 9095.06825 ,  5272.1758  , 29330.98315 ,  9301.89355 ,
       33750.2918  ,  4536.259   ,  2117.33885 , 14210.53595 ,
        3732.6251  , 10264.4421  , 18259.216   ,  7256.7231  ,
        3947.4131  , 46151.1245  , 48673.5588  , 44202.6536  ,
        9800.8882  , 42969.8527  ,  8233.0975  , 21774.32215 ,
        5080.096   ,  7441.501   ,  1256.299   ,  2755.02095 ,
       11085.5868  , 10923.9332  , 12644.589   , 18804.7524  ,
        9715.841   ,  1131.5066  , 15828.82173 , 11842.62375 ,
        2020.5523  ,  5693.4305  ,  2904.088   ,  7448.40395 ,
        2597.779   ,  7337.748   , 23887.6627  , 38709.176   ,
        4687.797   ,  2643.2685  , 11674.13    , 12124.9924  ,
        4889.9995  , 12333.828   ,  3579.8287  ,  4391.652   ,
       42124.5153  ,  4463.2051  , 13887.204   ,  1719.4363  ,
       28476.73499 ,  1708.92575 , 10594.2257  , 25333.33284 ,
        3645.0894  , 38746.3551  , 11848.141   , 10564.8845  ,
       13880.949   ,  4753.6368  , 27941.28758 ,  8017.

In [210]:
x_test[2]

array([64.   ,  0.   , 26.885,  0.   ,  1.   ,  1.   ])

In [211]:
x_test[2].shape

(6,)

In [212]:
x_test[2].reshape(1,6)

array([[64.   ,  0.   , 26.885,  0.   ,  1.   ,  1.   ]])

In [213]:
x_test[2].reshape(1,6).shape

(1, 6)

In [214]:
model_i.predict(x_test[2].reshape(1,6))

array([29627.69439108])

In [215]:
y_i[2]

29627.694391075875

In [216]:
# our model is able to predict correctly.