In [1]:
# import libraries
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
print("importing is done")

importing is done


In [2]:
#load the dataset
df = pd.read_csv('50_Startups.csv')

In [3]:
# summarizing the dataset
df

R&D Spend  Administration  Marketing Spend       State     Profit
0   165349.20       136897.80        471784.10    New York  192261.83
1   162597.70       151377.59        443898.53  California  191792.06
2   153441.51       101145.55        407934.54     Florida  191050.39
3   144372.41       118671.85        383199.62    New York  182901.99
4   142107.34        91391.77        366168.42     Florida  166187.94
5   131876.90        99814.71        362861.36    New York  156991.12
6   134615.46       147198.87        127716.82  California  156122.51
7   130298.13       145530.06        323876.68     Florida  155752.60
8   120542.52       148718.95        311613.29    New York  152211.77
9   123334.88       108679.17        304981.62  California  149759.96
10  101913.08       110594.11        229160.95     Florida  146121.95
11  100671.96        91790.61        249744.55  California  144259.40
12   93863.75       127320.38        249839.44     Florida  141585.52
13   91992.39       135495.07        252664.93  California  134307.35
14  119943.24       156547.42        256512.92     Florida  132602.65
15  114523.61       122616.84        261776.23    New York  129917.04
16   78013.11       121597.55        264346.06  California  126992.93
17   94657.16       145077.58        282574.31    New York  125370.37
18   91749.16       114175.79        294919.57     Florida  124266.90
19   86419.70       153514.11             0.00    New York  122776.86
20   76253.86       113867.30        298664.47  California  118474.03
21   78389.47       153773.43        299737.29    New York  111313.02
22   73994.56       122782.75        303319.26     Florida  110352.25
23   67532.53       105751.03        304768.73     Florida  108733.99
24   77044.01        99281.34        140574.81    New York  108552.04
25   64664.71       139553.16        137962.62  California  107404.34
26   75328.87       144135.98        134050.07     Florida  105733.54
27   72107.60       127864.55        353183.81    New York  105008.31
28   66051.52       182645.56        118148.20     Florida  103282.38
29   65605.48       153032.06        107138.38    New York  101004.64
30   61994.48       115641.28         91131.24     Florida   99937.59
31   61136.38       152701.92         88218.23    New York   97483.56
32   63408.86       129219.61         46085.25  California   97427.84
33   55493.95       103057.49        214634.81     Florida   96778.92
34   46426.07       157693.92        210797.67  California   96712.80
35   46014.02        85047.44        205517.64    New York   96479.51
36   28663.76       127056.21        201126.82     Florida   90708.19
37   44069.95        51283.14        197029.42  California   89949.14
38   20229.59        65947.93        185265.10    New York   81229.06
39   38558.51        82982.09        174999.30  California   81005.76
40   28754.33       118546.05        172795.67  California   78239.91
41   27892.92        84710.77        164470.71     Florida   77798.83
42   23640.93        96189.63        148001.11  California   71498.49
43   15505.73       127382.30         35534.17    New York   69758.98
44   22177.74       154806.14         28334.72  California   65200.33
45    1000.23       124153.04          1903.93    New York   64926.08
46    1315.46       115816.21        297114.46     Florida   49490.75
47       0.00       135426.92             0.00  California   42559.73
48     542.05        51743.15             0.00    New York   35673.41
49       0.00       116983.80         45173.06  California   14681.40

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 5 columns):
 #   Column           Non-Null Count  Dtype  
---  ------           --------------  -----  
 0   R&D Spend        50 non-null     float64
 1   Administration   50 non-null     float64
 2   Marketing Spend  50 non-null     float64
 3   State            50 non-null     object 
 4   Profit           50 non-null     float64
dtypes: float64(4), object(1)
memory usage: 2.1+ KB


In [5]:
len(df)

50

In [14]:
df.columns

Index(['R&D Spend', 'Administration', 'Marketing Spend', 'State', 'Profit'], dtype='object')

In [6]:
df.dtypes

R&D Spend          float64
Administration     float64
Marketing Spend    float64
State               object
Profit             float64
dtype: object

In [7]:
df.describe()

R&D Spend  Administration  Marketing Spend         Profit
count      50.000000       50.000000        50.000000      50.000000
mean    73721.615600   121344.639600    211025.097800  112012.639200
std     45902.256482    28017.802755    122290.310726   40306.180338
min         0.000000    51283.140000         0.000000   14681.400000
25%     39936.370000   103730.875000    129300.132500   90138.902500
50%     73051.080000   122699.795000    212716.240000  107978.190000
75%    101602.800000   144842.180000    299469.085000  139765.977500
max    165349.200000   182645.560000    471784.100000  192261.830000

In [ ]:
# wwe have 1 columns with object values which we have to convert to integer

In [8]:
# pre-processing the dataset
# first we check for null values
df.isnull().sum().max()

0

In [9]:
# we import new libraries to encode the columns with value as object
from sklearn import preprocessing
from sklearn.preprocessing import LabelEncoder

In [13]:
label = LabelEncoder()
label

LabelEncoder()

In [18]:
# Performing Label Encoding for "Gender Column"
df['State'] = label.fit_transform(df.State)

In [20]:
#this is our cleaned dataset
df

R&D Spend  Administration  Marketing Spend  State     Profit
0   165349.20       136897.80        471784.10      2  192261.83
1   162597.70       151377.59        443898.53      0  191792.06
2   153441.51       101145.55        407934.54      1  191050.39
3   144372.41       118671.85        383199.62      2  182901.99
4   142107.34        91391.77        366168.42      1  166187.94
5   131876.90        99814.71        362861.36      2  156991.12
6   134615.46       147198.87        127716.82      0  156122.51
7   130298.13       145530.06        323876.68      1  155752.60
8   120542.52       148718.95        311613.29      2  152211.77
9   123334.88       108679.17        304981.62      0  149759.96
10  101913.08       110594.11        229160.95      1  146121.95
11  100671.96        91790.61        249744.55      0  144259.40
12   93863.75       127320.38        249839.44      1  141585.52
13   91992.39       135495.07        252664.93      0  134307.35
14  119943.24       156547.42        256512.92      1  132602.65
15  114523.61       122616.84        261776.23      2  129917.04
16   78013.11       121597.55        264346.06      0  126992.93
17   94657.16       145077.58        282574.31      2  125370.37
18   91749.16       114175.79        294919.57      1  124266.90
19   86419.70       153514.11             0.00      2  122776.86
20   76253.86       113867.30        298664.47      0  118474.03
21   78389.47       153773.43        299737.29      2  111313.02
22   73994.56       122782.75        303319.26      1  110352.25
23   67532.53       105751.03        304768.73      1  108733.99
24   77044.01        99281.34        140574.81      2  108552.04
25   64664.71       139553.16        137962.62      0  107404.34
26   75328.87       144135.98        134050.07      1  105733.54
27   72107.60       127864.55        353183.81      2  105008.31
28   66051.52       182645.56        118148.20      1  103282.38
29   65605.48       153032.06        107138.38      2  101004.64
30   61994.48       115641.28         91131.24      1   99937.59
31   61136.38       152701.92         88218.23      2   97483.56
32   63408.86       129219.61         46085.25      0   97427.84
33   55493.95       103057.49        214634.81      1   96778.92
34   46426.07       157693.92        210797.67      0   96712.80
35   46014.02        85047.44        205517.64      2   96479.51
36   28663.76       127056.21        201126.82      1   90708.19
37   44069.95        51283.14        197029.42      0   89949.14
38   20229.59        65947.93        185265.10      2   81229.06
39   38558.51        82982.09        174999.30      0   81005.76
40   28754.33       118546.05        172795.67      0   78239.91
41   27892.92        84710.77        164470.71      1   77798.83
42   23640.93        96189.63        148001.11      0   71498.49
43   15505.73       127382.30         35534.17      2   69758.98
44   22177.74       154806.14         28334.72      0   65200.33
45    1000.23       124153.04          1903.93      2   64926.08
46    1315.46       115816.21        297114.46      1   49490.75
47       0.00       135426.92             0.00      0   42559.73
48     542.05        51743.15             0.00      2   35673.41
49       0.00       116983.80         45173.06      0   14681.40

In [21]:
# we confrm the type of value of the sex column
type(df.State)

pandas.core.series.Series

In [22]:
# Now we create x (input) and y (output) variable
x=df.iloc[:,:-1].values
y=df.iloc[:,-1].values

In [23]:
x

array([[1.6534920e+05, 1.3689780e+05, 4.7178410e+05, 2.0000000e+00],
       [1.6259770e+05, 1.5137759e+05, 4.4389853e+05, 0.0000000e+00],
       [1.5344151e+05, 1.0114555e+05, 4.0793454e+05, 1.0000000e+00],
       [1.4437241e+05, 1.1867185e+05, 3.8319962e+05, 2.0000000e+00],
       [1.4210734e+05, 9.1391770e+04, 3.6616842e+05, 1.0000000e+00],
       [1.3187690e+05, 9.9814710e+04, 3.6286136e+05, 2.0000000e+00],
       [1.3461546e+05, 1.4719887e+05, 1.2771682e+05, 0.0000000e+00],
       [1.3029813e+05, 1.4553006e+05, 3.2387668e+05, 1.0000000e+00],
       [1.2054252e+05, 1.4871895e+05, 3.1161329e+05, 2.0000000e+00],
       [1.2333488e+05, 1.0867917e+05, 3.0498162e+05, 0.0000000e+00],
       [1.0191308e+05, 1.1059411e+05, 2.2916095e+05, 1.0000000e+00],
       [1.0067196e+05, 9.1790610e+04, 2.4974455e+05, 0.0000000e+00],
       [9.3863750e+04, 1.2732038e+05, 2.4983944e+05, 1.0000000e+00],
       [9.1992390e+04, 1.3549507e+05, 2.5266493e+05, 0.0000000e+00],
       [1.1994324e+05, 1.5654742e+

In [24]:
y

array([192261.83, 191792.06, 191050.39, 182901.99, 166187.94, 156991.12,
       156122.51, 155752.6 , 152211.77, 149759.96, 146121.95, 144259.4 ,
       141585.52, 134307.35, 132602.65, 129917.04, 126992.93, 125370.37,
       124266.9 , 122776.86, 118474.03, 111313.02, 110352.25, 108733.99,
       108552.04, 107404.34, 105733.54, 105008.31, 103282.38, 101004.64,
        99937.59,  97483.56,  97427.84,  96778.92,  96712.8 ,  96479.51,
        90708.19,  89949.14,  81229.06,  81005.76,  78239.91,  77798.83,
        71498.49,  69758.98,  65200.33,  64926.08,  49490.75,  42559.73,
        35673.41,  14681.4 ])

In [25]:
# now we import additionl required libraries
from sklearn.model_selection import train_test_split
from sklearn.ensemble import GradientBoostingRegressor
from sklearn.metrics import mean_squared_error
print("importing is done")

importing is done


In [26]:
# now we create training and testing dataset
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)

In [27]:
x_train.shape,x_test.shape,y_train.shape,y_test.shape

((40, 4), (10, 4), (40,), (10,))

In [28]:
x_test

array([[9.1992390e+04, 1.3549507e+05, 2.5266493e+05, 0.0000000e+00],
       [3.8558510e+04, 8.2982090e+04, 1.7499930e+05, 0.0000000e+00],
       [6.1994480e+04, 1.1564128e+05, 9.1131240e+04, 1.0000000e+00],
       [1.0002300e+03, 1.2415304e+05, 1.9039300e+03, 2.0000000e+00],
       [9.4657160e+04, 1.4507758e+05, 2.8257431e+05, 2.0000000e+00],
       [5.4205000e+02, 5.1743150e+04, 0.0000000e+00, 2.0000000e+00],
       [7.5328870e+04, 1.4413598e+05, 1.3405007e+05, 1.0000000e+00],
       [6.4664710e+04, 1.3955316e+05, 1.3796262e+05, 0.0000000e+00],
       [6.3408860e+04, 1.2921961e+05, 4.6085250e+04, 0.0000000e+00],
       [8.6419700e+04, 1.5351411e+05, 0.0000000e+00, 2.0000000e+00]])

In [29]:
model_start = GradientBoostingRegressor()
model_start

GradientBoostingRegressor()

In [30]:
# we fit the training data in our model
model_start.fit(x_train,y_train)

GradientBoostingRegressor()

In [31]:
# Now testing new Model prediction by providing Test Data set
y_start = model_start.predict(x_test)

In [32]:
# this is our variable which has learned the test data
y_start

array([127678.28969396,  86262.18177996,  94258.57713086,  54735.71965557,
       133645.3307933 ,  34007.2798154 , 115673.03235936,  99711.39331254,
        81517.91633421, 110973.39206903])

In [33]:
# Compare predictions with testing data given
# this will only give accuracy
mse = mean_squared_error(y_test, y_start)
print(mse)

82934247.08565582


In [38]:
# if we keep split as 70/30
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.3,random_state=42)
model_start = GradientBoostingRegressor()
model_start.fit(x_train,y_train)
y_start = model_start.predict(x_test)
mse = mean_squared_error(y_test, y_start)
print(mse)

111906114.01788841


In [39]:
# Predicting the output of single test data using our trained model
y_test

array([134307.35,  81005.76,  99937.59,  64926.08, 125370.37,  35673.41,
       105733.54, 107404.34,  97427.84, 122776.86, 141585.52, 166187.94,
        89949.14, 152211.77, 182901.99])

In [40]:
x_test[2]

array([6.1994480e+04, 1.1564128e+05, 9.1131240e+04, 1.0000000e+00])

In [41]:
x_test[2].shape

(4,)

In [42]:
x_test[2].reshape(1,4)

array([[6.1994480e+04, 1.1564128e+05, 9.1131240e+04, 1.0000000e+00]])

In [43]:
x_test[2].reshape(1,4).shape

(1, 4)

In [48]:
model_start.predict(x_test[2].reshape(1,4))

array([96731.38195472])

In [49]:
y_start[2]

96731.38195471975

In [ ]:
# our model is able to predict correctly.