In [1]:
# import libraries
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
print("importing is done")

importing is done


In [2]:
#loaad the dataset
df = pd.read_csv('concrete_data.csv')

In [3]:
# summarizing the dataset
df

Cement  Blast Furnace Slag  Fly Ash  Water  Superplasticizer  \
0      540.0                 0.0      0.0  162.0               2.5   
1      540.0                 0.0      0.0  162.0               2.5   
2      332.5               142.5      0.0  228.0               0.0   
3      332.5               142.5      0.0  228.0               0.0   
4      198.6               132.4      0.0  192.0               0.0   
...      ...                 ...      ...    ...               ...   
1025   276.4               116.0     90.3  179.6               8.9   
1026   322.2                 0.0    115.6  196.0              10.4   
1027   148.5               139.4    108.6  192.7               6.1   
1028   159.1               186.7      0.0  175.6              11.3   
1029   260.9               100.5     78.3  200.6               8.6   

      Coarse Aggregate  Fine Aggregate  Age  Strength  
0               1040.0           676.0   28     79.99  
1               1055.0           676.0   28     61.89  
2                932.0           594.0  270     40.27  
3                932.0           594.0  365     41.05  
4                978.4           825.5  360     44.30  
...                ...             ...  ...       ...  
1025             870.1           768.3   28     44.28  
1026             817.9           813.4   28     31.18  
1027             892.4           780.0   28     23.70  
1028             989.6           788.9   28     32.77  
1029             864.5           761.5   28     32.40  

[1030 rows x 9 columns]

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1030 entries, 0 to 1029
Data columns (total 9 columns):
 #   Column              Non-Null Count  Dtype  
---  ------              --------------  -----  
 0   Cement              1030 non-null   float64
 1   Blast Furnace Slag  1030 non-null   float64
 2   Fly Ash             1030 non-null   float64
 3   Water               1030 non-null   float64
 4   Superplasticizer    1030 non-null   float64
 5   Coarse Aggregate    1030 non-null   float64
 6   Fine Aggregate      1030 non-null   float64
 7   Age                 1030 non-null   int64  
 8   Strength            1030 non-null   float64
dtypes: float64(8), int64(1)
memory usage: 72.6 KB


In [5]:
len(df)

1030

In [6]:
df.describe()

Cement  Blast Furnace Slag      Fly Ash        Water  \
count  1030.000000         1030.000000  1030.000000  1030.000000   
mean    281.167864           73.895825    54.188350   181.567282   
std     104.506364           86.279342    63.997004    21.354219   
min     102.000000            0.000000     0.000000   121.800000   
25%     192.375000            0.000000     0.000000   164.900000   
50%     272.900000           22.000000     0.000000   185.000000   
75%     350.000000          142.950000   118.300000   192.000000   
max     540.000000          359.400000   200.100000   247.000000   

       Superplasticizer  Coarse Aggregate  Fine Aggregate          Age  \
count       1030.000000       1030.000000     1030.000000  1030.000000   
mean           6.204660        972.918932      773.580485    45.662136   
std            5.973841         77.753954       80.175980    63.169912   
min            0.000000        801.000000      594.000000     1.000000   
25%            0.000000        932.000000      730.950000     7.000000   
50%            6.400000        968.000000      779.500000    28.000000   
75%           10.200000       1029.400000      824.000000    56.000000   
max           32.200000       1145.000000      992.600000   365.000000   

          Strength  
count  1030.000000  
mean     35.817961  
std      16.705742  
min       2.330000  
25%      23.710000  
50%      34.445000  
75%      46.135000  
max      82.600000

In [7]:
df.dtypes

Cement                float64
Blast Furnace Slag    float64
Fly Ash               float64
Water                 float64
Superplasticizer      float64
Coarse Aggregate      float64
Fine Aggregate        float64
Age                     int64
Strength              float64
dtype: object

In [8]:
#since all the values are numerical we can proceed further 

In [9]:
# pre-processing the dataset
# first we check for null values
df.isnull().sum().max

<bound method Series.max of Cement                0
Blast Furnace Slag    0
Fly Ash               0
Water                 0
Superplasticizer      0
Coarse Aggregate      0
Fine Aggregate        0
Age                   0
Strength              0
dtype: int64>

In [28]:
# we do not have any null values in this dataset
# now we create x as in put and y as output
x = df.iloc[:,:-1].values
y = df.iloc[:,-1].values

In [29]:
x.shape

(1030, 8)

In [30]:
y.shape

(1030,)

In [31]:
# now we import additionl required libraries
from sklearn.model_selection import train_test_split
from sklearn.ensemble import GradientBoostingRegressor
from sklearn.metrics import mean_squared_error
print("importing is done")

importing is done


In [32]:
# now we create training and testing dataset
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)

In [33]:
x_train.shape, x_test.shape, y_train.shape, y_test.shape

((824, 8), (206, 8), (824,), (206,))

In [34]:
# now we create a model
model_c = GradientBoostingRegressor()
model_c

GradientBoostingRegressor()

In [35]:
#now we train the model
model_c.fit(x_train, y_train)

GradientBoostingRegressor()

In [37]:
# now we predict the result by providing the test data
y_c = model_c.predict(x_test)
y_c

array([48.97709196, 45.76321527, 69.29974613, 34.17165924, 13.54345015,
       42.78513374, 25.79041357, 50.55478217, 30.7921554 , 41.47610681,
       40.01980445, 15.52875237, 40.65048559, 42.39599239, 29.5259735 ,
       21.94430917, 36.8486475 , 19.88376954, 37.89734327, 29.74477933,
       39.2997397 , 38.69568425, 46.33504461, 10.95944287, 38.42206553,
       33.32891578, 10.03105277, 45.5796405 , 54.05249279, 12.82847036,
       49.94238443, 35.19920787, 46.83674447, 54.69618672, 17.39000746,
       35.31605575, 30.68173036, 42.80178697, 11.83869237, 47.71032557,
       15.7795485 ,  8.24559792, 37.58230776, 51.75869738, 11.42913182,
       75.79862669, 52.22575223, 34.53187655, 26.53566374,  8.35007739,
       46.41337261, 41.18517313, 25.8584379 , 17.71344231, 41.89081029,
       33.73868877, 26.90181879,  9.29341699, 37.69299106, 23.60805537,
       43.49241388, 13.98646545, 38.11599427, 50.99401406, 31.21076577,
       24.52173979, 31.94921772, 15.47461954, 33.17564059, 23.84

In [38]:
# Compare predictions with testing data given
# this will only give accuracy
mse = mean_squared_error(y_test, y_c)
print(mse)

30.232413016690657


In [39]:
# if we keep split as 70/30
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.3,random_state=42)
model_c = GradientBoostingRegressor()
model_c.fit(x_train,y_train)
y_c = model_c.predict(x_test)
mse = mean_squared_error(y_test, y_c)
print(mse)

29.34282010650113


In [40]:
# so here we can see that assigning 70/30 split gives a better performance

In [42]:
# Predicting the output of single test data using our trained model
y_test[1]

55.9

In [44]:
x_test[1]

array([362.6, 189. ,   0. , 164.9,  11.6, 944.7, 755.8,   7. ])

In [45]:
x_test[1].shape

(8,)

In [47]:
x_test[1].reshape(1,8)

array([[362.6, 189. ,   0. , 164.9,  11.6, 944.7, 755.8,   7. ]])

In [48]:
x_test[1].reshape(1,8).shape

(1, 8)

In [50]:
model_c.predict(x_test[1].reshape(1,8))

array([45.09499094])

In [52]:
y_c[1]

45.09499094236013

In [ ]:
# our model is able to predict correctly.